# Generated by Django 5.0.6 on 2024-05-21 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_passkey_passkey_passkey_repository'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='picture_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
