# Generated by Django 5.0.6 on 2024-05-21 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_repository_picture_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='repository_pictures/'),
        ),
    ]
