# Generated by Django 5.0.6 on 2024-05-21 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_repository_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repository',
            name='picture_url',
        ),
    ]
