# Generated by Django 5.0.6 on 2024-06-10 16:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_onetimeimagekey'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='onetimeimagekey',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='imagekey', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='passkey',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='passkey', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='securityquestion',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='security_questions', to=settings.AUTH_USER_MODEL),
        ),
    ]
